version: '3.8'
services:
  app-python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: python app.py
    restart: always

  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:7.5.2
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
      - my-network
    ports:
      - "3000:3000"
    restart: always

networks:
  my-network:
