version: '3.8'

services:
  app-python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always

  prometheus:
    image: ubuntu/prometheus:latest
    ports:
      - "9000:9000"
    command: ["prometheus"]
    restart: always

  grafana:
    image: bitnami/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always